apiVersion: v1
kind: ConfigMap
metadata:
  name: robodoc-backend-production
  namespace: robodoc
data:
  ALLOWED_ORIGIN: "*"
  APP_DEBUG: "true"
  APP_ENV: production
  APP_NAME: "Robodoc Limited"
  APP_URL: "https://admin.domain.com"
  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: ap-southeast-1
  AWS_SECRET_ACCESS_KEY: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  AZURE_CONNECTION_STRING: ""
  AZURE_STORAGE_CONTAINER: production
  AZURE_STORAGE_KEY: ""
  AZURE_STORAGE_NAME: ""
  AZURE_STORAGE_URL: ""

  BKASH_PAYMENT_ENV: production
  BKASH_USER_NAME: ""

  CACHE_DRIVER: redis
  CACHE_PREFIX: robodoc_production
  CACHE_STORE: redis

  BRAND_BANNER_PATH: ""
  BRAND_LOGO_PATH: ""
  BROADCAST_DRIVER: log
  CATEGORY_BANNER_PATH: ""
  CATEGORY_LOGO_PATH: ""
  COMPANY_ADDRESS: ""
  COMPANY_PHONE_NUMBER: ""
  CONSUMER_SSG_SECRET: ""

  DB_CONNECTION: mysql
  DB_DATABASE: robodoc_production
  DB_HOST: ""
  DB_PORT: ""
  DB_ROBODOC_DATABASE: robodocbd
  DB_ROBODOC_HOST: ""
  DB_USERNAME: ""

  DIGITALOCEAN_BUCKET: ""
  DIGITALOCEAN_CDN: ""
  DIGITALOCEAN_DEFAULT_REGION: sgp1
  DIGITALOCEAN_ENDPOINT: ""
  DIGITALOCEAN_VISIBILITY: public

  ELASTICSEARCH_HOST: ""
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_USER: elastic

  REDIS_HOST: ""
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"

  FILAMENT_FILESYSTEM_DISK: digitalocean
  FILAMENT_FILESYSTEM_DRIVER: digitalocean
  FILESYSTEM_DISK: public

  FORMS_FILESYSTEM_DRIVER: digitalocean
  FRONTEND_CONSUMER: ""
  GOOGLE_RECAPTCHA_SKIP_IP: ""
  HASH_ALGORITHM: sha256
  HASH_SECRET_KEY: ""
  IK_MAIL_ENCRYPTION: ssl
  IK_MAIL_FROM_ADDRESS: ""
  IK_MAIL_FROM_NAME: ""
  IK_MAIL_HOST: ""
  IK_MAIL_PORT: "587"
  IK_MAIL_USERNAME: ""
  INNOVATION_KIT_CONSUMER_SSG_SECRET: ""
  INNOVATION_KIT_FRONTEND_CONSUMER: ""
  INNOVATION_KIT_SEO_BANNER_PATH: ""
  JWT_ALGORITHM: HS256
  LOG_CHANNEL: stderr
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug
  MAIL_ENCRYPTION: ssl
  MAIL_FROM_ADDRESS: ""
  MAIL_FROM_NAME: ""
  MAIL_HOST: ""
  MAIL_MAILER: robodoc
  MAIL_PORT: "587"
  MAIL_USERNAME: ""
  MEDIA_DISK: digitalocean
  MEDIA_LIBRARY_DISK: digitalocean
  MEMCACHED_HOST: 127.0.0.1
  MESSAGE_SENT_IN_PHONE: "true"
  PAYMENT_ENV: sandbox
  PAYMENT_SUCCESS_REDIRECT_URL: order
  PUSHER_APP_CLUSTER: mt1
  PUSHER_APP_ID: ""
  PUSHER_APP_SECRET: ""
  PUSHER_HOST: ""
  PUSHER_PORT: "443"
  PUSHER_SCHEME: https
  QUEUE_CONNECTION: redis
  REDX_ENVIRONMENT: production
  REDX_PERCENT_OF_EXTRA_CHARGE: "1"
  REDX_STORE_PICKUP_ID: ""
  REQUEST_BY_MOBILE_APP: ""
  REQUEST_BY_MOBILE_APP_VALUE: ""
  ROBODOC_CONSUMER_SSG_SECRET: ""
  ROBODOC_FRONTEND_CONSUMER: ""
  ROBODOC_SEO_BANNER_PATH: ""
  SCOUT_PREFIX: robodoc_production_
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"
  SMS_SEND_MAX_LIMIT_BY_URL_PER_DAY: "3"
  SSL_WIRELESS_MESSAGE_API_TOKEN: ""
  SSL_WIRELESS_MESSAGE_API_URL: ""
  SSL_WIRELESS_MESSAGE_CSMS_ID: ""
  SSLWIRELESS_PAYMENT_ENV: production
  SSLWIRELESS_STORE_ID: ""
  STATIC_IMAGE_BASE_URL: ""
  TABLES_FILESYSTEM_DRIVER: digitalocean
  TEST_DATA_SEED: "false"
  TOGGLE_APP_SERVICES: "true"
  TRUSTED_PROXIES: '*'
  VITE_PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
  VITE_PUSHER_HOST: ${PUSHER_HOST}
  VITE_PUSHER_PORT: ${PUSHER_PORT}
  VITE_PUSHER_SCHEME: ${PUSHER_SCHEME}
  WEB_BASIC_AUTH_PASSWORD: ""
  WEB_BASIC_AUTH_USERNAME: ""
  HOST_TYPE: k8s
