apiVersion: v1
kind: Secret
metadata:
  name: robodoc-backend-production
  namespace: robodoc
type: Opaque
stringData:
  DIGITALOCEAN_SECRET_ACCESS_KEY: ""
  DIGITALOCEAN_ACCESS_KEY_ID: ""
  BKASH_APP_KEY: ""
  BKASH_APP_SECRET: ""
  BKASH_PASSWORD: ""
  DB_PASSWORD: ""
  IK_MAIL_PASSWORD: ""
  MAIL_PASSWORD: ""
  GOOGLE_RECAPTCHA_SECRET_KEY: ""
  GOOGLE_RECAPTCHA_SITE_KEY: ""
  APP_KEY: ""
  SSLWIRELESS_STORE_PASSWORD: ""
  JWT_SECRET_KEY: ""
  ELASTICSEARCH_PASSWORD: ""
  REDX_API_TOKEN: ""
  REDIS_PASSWORD: ""
