apiVersion: v1
kind: Service
metadata:
  name: robodoc-backend-production
  namespace: robodoc
spec:
  type: ClusterIP
  selector:
    app: robodoc-backend-production
  ports:
    - protocol: TCP
      port: 80           # Service port
      targetPort: 80     # Pod container port
