apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: logging

data:
  vector.yaml: |
    data_dir: /var/lib/vector

    sources:
      kubernetes_logs:
        type: kubernetes_logs

    transforms:
      ...
      ...

    sinks:
      elasticsearch:
        type: elasticsearch
        ...