apiVersion: v1
kind: Secret
metadata:
  name: robodoc-customer-production
  namespace: robodoc
type: Opaque
stringData:
  BACKEND_SECRET_TOKEN: ""
  GOOGLE_CLIENT_SECRET: ""
  NEXTAUTH_SECRET: ""
  NEXT_PUBLIC_JWT_SECRET_TOKEN: ""
  GOOGLE_CLIENT_ID: ""