apiVersion: v1
kind: Service
metadata:
  name: robodoc-customer-production
  namespace: robodoc
spec:
  type: ClusterIP
  selector:
    app: robodoc-customer-production
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000